# Generated by Django 3.2.25 on 2024-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20240402_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
