# Generated by Django 3.2.25 on 2024-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_usuario_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
