# Generated by Django 3.2.25 on 2024-04-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_usuarioevento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha_final',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_inicio',
        ),
    ]
