# Generated by Django 3.2.25 on 2024-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20240416_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='titulo_evento',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
