# Generated by Django 3.2.25 on 2024-04-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_evento_titulo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
