# Generated by Django 5.0.4 on 2024-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20240422_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='localizacion_event_string',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
