# Generated by Django 5.0.4 on 2024-05-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_evento_localizacion_event_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='localizacion_event_string',
            new_name='localizacion_evento_string',
        ),
    ]
