# Generated by Django 3.2.12 on 2024-05-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_rename_localizacion_event_string_evento_localizacion_evento_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia_usuario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intereses_usuario',
            field=models.CharField(blank=True, choices=[('Juegos', 'Juegos'), ('Fiestas', 'Fiestas'), ('Musica', 'Música'), ('Social', 'Social'), ('Deportes', 'Deportes'), ('Viajes', 'Viajes'), ('Lectura', 'Lectura'), ('Cocina', 'Cocina'), ('Fotografía', 'Fotografía'), ('Tecnología', 'Tecnología'), ('Arte', 'Arte'), ('Naturaleza', 'Naturaleza'), ('Películas', 'Películas'), ('Baile', 'Baile'), ('Moda', 'Moda'), ('Meditación', 'Meditación'), ('Voluntariado', 'Voluntariado'), ('Yoga', 'Yoga'), ('Animales', 'Animales'), ('Astronomía', 'Astronomía')], max_length=50, null=True),
        ),
    ]
