# Generated by Django 3.2.12 on 2024-05-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_notificacionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionusuario',
            name='notification_type',
            field=models.CharField(default='dropUserOnEvent', max_length=100),
            preserve_default=False,
        ),
    ]
