# Generated by Django 5.0.4 on 2024-05-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_notificacionusuario_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amistad_aceptada', models.BooleanField()),
                ('usuario_enviador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_enviador_solicitud_amistad', to='data.usuario')),
                ('usuario_recibidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_recibidor_solicitud_amistad', to='data.usuario')),
            ],
        ),
    ]
