# Generated by Django 5.0.4 on 2024-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_amistad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='intereses_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='intereses_usuario',
            field=models.ManyToManyField(blank=True, to='data.interes'),
        ),
    ]
