# Generated by Django 5.0.4 on 2024-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_interes_remove_usuario_intereses_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='intereses_evento',
            field=models.ManyToManyField(blank=True, to='data.interes'),
        ),
    ]
